### ISSUE TITLE
WS2812B breakout board

### ISSUE THREAD

**Issue by silviudc** [WhoTheHeck/ESP8266-Multisensor#2]
Hi, I'm having trouble finding this particular type of led breakout board you have:
![image](https://user-images.githubusercontent.com/17740184/192136654-6cc6fe6d-e91a-49d4-b24b-3642cce636c7.png)

Everything I found on a breakout board has the pins in the wrong order so it won't work on the PCB (which I have already ordered)
Any suggestions? Or could you share the exact model number and place you purchased them from?

Thanks

**Comment by WhoTheHeck** [comment]
I got mine from ebay. Searching for "WS2812B 1-Bit Module" I still find this exact board from different sellers, typically located in China.

**Comment by silviudc** [comment]
Great, thanks for the suggestion, bought a few :)
