### ISSUE TITLE
Fresnel lens size

### ISSUE THREAD

**Issue by silviudc** [WhoTheHeck/ESP8266-Multisensor#3]
Any idea which lens size fits perfectly in the 3d printed case?

The one linked [here ](https://www.aliexpress.com/item/4000851822692.html?aff_fcid=54b5d916337243ee8088c7a958d43c87-1665060434775-05442-_A5kIed&aff_fsk=_A5kIed&aff_platform=shareComponent-detail&sk=_A5kIed&aff_trace_key=54b5d916337243ee8088c7a958d43c87-1665060434775-05442-_A5kIed&terminal_id=cc6d221ca53b42f7b72c8cb44af9dd51&afSmartRedirect=y )has three sizes.

![image](https://user-images.githubusercontent.com/17740184/194316932-4a1c481b-216d-419a-a6c7-1d5919cf1873.png)

**Comment by WhoTheHeck** [comment]
Sorry I seem to not get notifications for new issues. Can you add the information for which lens is the correct one if you already found the answer? 😇

**Comment by silviudc** [comment]
I went for the middle one 12.8 as that is the size of the lens some of the am311 sensors I have, will see if it fits when it arrives.
